"""Garantindo todas as tabelas dos modelos

Revision ID: 1bf51b91a2aa
Revises: cc6705064f1e
Create Date: 2025-05-19 23:36:24.180951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf51b91a2aa'
down_revision = 'cc6705064f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ronda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inicio_ronda', sa.DateTime(), nullable=True),
    sa.Column('fim_ronda', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ronda_fim_ronda'), ['fim_ronda'], unique=False)
        batch_op.create_index(batch_op.f('ix_ronda_inicio_ronda'), ['inicio_ronda'], unique=False)

    op.create_table('ocorrencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ronda_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ronda_id'], ['ronda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ocorrencia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ocorrencia_timestamp'), ['timestamp'], unique=False)

    op.create_table('ponto_ronda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('timestamp_verificacao', sa.DateTime(), nullable=True),
    sa.Column('ronda_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ronda_id'], ['ronda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('user_agent',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_index('ix_login_history_timestamp')
        batch_op.drop_index('ix_login_history_user_id')
        batch_op.drop_column('success')
        batch_op.drop_column('attempted_username')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=64),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.drop_column('is_admin')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=False))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempted_username', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('success', sa.BOOLEAN(), nullable=False))
        batch_op.create_index('ix_login_history_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_login_history_timestamp', ['timestamp'], unique=False)
        batch_op.alter_column('user_agent',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('ponto_ronda')
    with op.batch_alter_table('ocorrencia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocorrencia_timestamp'))

    op.drop_table('ocorrencia')
    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ronda_inicio_ronda'))
        batch_op.drop_index(batch_op.f('ix_ronda_fim_ronda'))

    op.drop_table('ronda')
    # ### end Alembic commands ###
